# Generated by Django 3.1 on 2021-01-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('func_name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('finished', 'finished'), ('failed', 'failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('argument', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
