# Generated by Django 3.1 on 2021-01-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
        ('periodtask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='argument',
        ),
        migrations.RemoveField(
            model_name='job',
            name='func_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='task_name',
        ),
        migrations.AddField(
            model_name='job',
            name='periodtask',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('pending', 'pending'), ('finished', 'finished'), ('failed', 'failed')], max_length=20),
        ),
    ]
